### ISSUE TITLE
We have purchased this .NET Huge Extension-methods Collection but when we add the same to our solution in Winforms project of .net it is giving error for dll added. Reference not found even though reference added properly and file copied to bin folder.

### ISSUE THREAD

**Issue by infotronicx** [ElektroStudios/DevCase.github.io#1]
We have purchased this .NET Huge Extension-methods Collection but when we add the same to our solution in Winforms project of .net it is giving error for dll added. Reference not found even though reference added properly and file copied to bin folder.

**Comment by ElektroStudios** [comment]
Dear @infotronicx,

Thank you for your recent purchase.

I understand that we are not discussing the **DevCase** product, but rather a different product titled '`.NET Huge Extension-methods Collection`', which is distributed through a DLL file named **ElektroExtensions.dll**.

If possible and permitted, please consider submitting your solution (or a sample to reproduce the issue) for review by sending it to [CSG1986@hotmail.com](mailto:CSG1986@hotmail.com). Your project will be treated with complete confidentiality, and having direct access to the solution files will likely help us most in locating the exact problem and offering you a solution.

-------------------------

In any case, could you please confirm whether your WinForms solution is based on the .NET Framework?

Please note that the DLL file named **ElektroExtensions.dll** is designed for solutions based on the .NET Framework, starting from .NET Framework 4.0 up to 4.6 (all the DLL files will work on .NET Framework 4.7.x, 4.8 and 4.8.1). It will not run on .NET / .NET Core, and this may cause assembly reference issues.

-------------------------

Additionally, please let me tell you that the **DevCase** product, which is what this GitHub repository is linked to, it is a product in constant development, continually evolving, it includes all the features that you may find in the **ElektroExtensions.dll** DLL file, and It comes in two distributions: one designed for .NET Framework 4.8 and 4.8.1, and the other designed to work from .NET 6 up to version 8.x. 

You may consider to request a refund through **Envato** market for the `.NET Huge Extension-methods Collection`' product then check out **DevCase** product only in case of your solution targets .NET instead of the .NET Framework and you are looking for a similar product that works on .NET and that has all the features you are looking for.

Thank you for your understanding. I look forward to resolving any outstanding issues together.

Best regards.

**Comment by infotronicx** [comment]
Pls process the refund I will go ahead with the dev case

Shaan Dudhia

Director, Infotronicx Private Limited
1-800-889-6204  9825471413  ***@***.***
714, Shivalik Shilp 2, Judges Bungalow Rd, opp. ITC Narmada Hotel, Nr.
Shivranjani Cross Road, Satellite, Ahmedabad, Gujarat 380015
https://www.infotronicx.com
<https://www.facebook.com/infotronicx>
<https://www.linkedin.com/company/the-infotronicx>
<https://twitter.com/infotronicx>
  Click to schedule a meeting
***@***.***>
***@***.***>

Please consider your environmental responsibility. Before printing this
e-mail message, ask yourself whether you really need a hard copy.

​CONFIDENTIAL COMMUNICATION: This email message and any attachments may
contain privileged and confidential information intended only for the use
of the individual or entity to which the email is addressed. If the reader
of this message is not the intended recipient or the employee or agent
responsible to deliver it to the intended recipient, that person is hereby
notified that any dissemination, distribution or copying of this
communication is prohibited. If you have received this communication in
error, please notify us as soon as possible by telephone (collect calls
will be accepted). Thank you for your cooperation and assistance.

**Comment by ElektroStudios** [comment]
> Pls process the refund I will go ahead with the dev case 

You require to use the refund request form on **Envato** / **Codecanyon** in order for me to approve the refund request, please check this:

> Customers can submit a refund request through the refund request form. In the majority of cases for Theme, Web and Code items, when a refund request is submitted it goes to the author of the item for approval. On submission, customers will receive an email with a link to raise a dispute if they don’t hear from you within 5 days.

 - Source: https://help.author.envato.com/hc/en-us/articles/360000472063-Refunds-for-ThemeForest-and-CodeCanyon#h_01EZ66APM48KXP8174BN4MFZ77

A refund request button may appear on the product page:

 - https://codecanyon.net/item/net-huge-extensionmethods-collection/19254904#

Or you can follow the next link in order to make a refund request:

 - https://codecanyon.net/refund_requests/new
 
 I am sorry for any confusion and/or problems and inconvenience that the product `.NET Huge Extension-methods Collection` has caused.

**Comment by ElektroStudios** [comment]
I'm sorry for the delay, the refund was approved a few minutes ago: 

![WinSnap 01](https://github.com/ElektroStudios/DevCase.github.io/assets/13082613/fb2041cb-5630-4f42-a684-5cc1a9dab54a)

The Envato Help team are now on it and they will process the request in 3-5 business days.
 
If do you still have any question, please feel free to reopen this thread.

Sincerely, 
ElektroStudios.
